# Generated by Django 6.0 on 2026-04-14 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.CharField(help_text="e.g. 'python', 'fullstack'", max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(help_text='Price in INR')),
                ('original_price', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('lessons', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('accent_color', models.CharField(default='#00d4ff', max_length=20)),
                ('icon', models.CharField(default='bi-easel2', max_length=50)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='#00d4ff', max_length=20)),
                ('topics', models.JSONField(default=list, help_text='List of topic strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('course_name', models.CharField(max_length=150)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paise (INR x 100)')),
                ('payment_method', models.CharField(default='razorpay', max_length=50)),
                ('external_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactapi.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='course_videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='contactapi.course')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(max_length=100)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paise or cents')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('method', models.CharField(default='razorpay', max_length=50)),
                ('paid_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='contactapi.courseenrollment')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
